#!/bin/tcsh -f
# petsurfer-km - BIDS app to run invividual PETsurfer kinetic modeling after running petsurfer-prep

if($?FREESURFER_HOME) then
  if(-e $FREESURFER_HOME/sources.csh) then
    source $FREESURFER_HOME/sources.csh
  endif
endif

set VERSION = '$Id$';
set scriptname = `basename $0`

set sif = ()
set bidsdir = ()
set outdir = ()
set analysislevel = ()
set fslicense = ()
set LF = /dev/null
set pskmargs = ()
set container = apptainer

set inputargs = ($argv);
set PrintHelp = 0;
if($#argv == 0) goto usage_exit;
#set n = `echo $argv | grep -e -help | wc -l` 
#if($n != 0) then
#  set PrintHelp = 1;
#  goto usage_exit;
#endif
set n = `echo $argv | grep -e -version | wc -l` 
if($n != 0) then
  echo $VERSION
  exit 0;
endif
goto parse_args;
parse_args_return:
goto check_params;
check_params_return:

set StartTime = `date`;
set tSecStart = `date '+%s'`;
set year  = `date +%Y`
set month = `date +%m`
set day   = `date +%d`
set hour   = `date +%H`
set min    = `date +%M`

#========================================================
#  -B ${work}:/work \

set cmd = ($container run \
  -B ${bidsdir}:/data/input:ro \
  -B ${outdir}:/data/output \
  -B ${fslicense}:/license.txt:ro \
  --pwd /data/output \
  --env FS_LICENSE=/license.txt \
  $sif petsurfer-km /data/input /data/output $analysislevel $pskmargs)
echo "--------------------------------------------------------"
echo $cmd
echo "--------------------------------------------------------"
$cmd
if($status) exit 1

#========================================================

# Done
echo " " |& tee -a $LF
set tSecEnd = `date '+%s'`;
@ tSecRun = $tSecEnd - $tSecStart;
set tRunMin = `echo $tSecRun/60|bc -l`
set tRunMin = `printf %5.2f $tRunMin`
set tRunHours = `echo $tSecRun/3600|bc -l`
set tRunHours = `printf %5.2f $tRunHours`
echo "Started at $StartTime " |& tee -a $LF
echo "Ended   at `date`" |& tee -a $LF
echo "Petsurfer-Km-Run-Time-Sec $tSecRun" |& tee -a $LF
echo "Petsurfer-Km-Run-Time-Min $tRunMin" |& tee -a $LF
echo "Petsurfer-Km-Run-Time-Hours $tRunHours" |& tee -a $LF
echo " " |& tee -a $LF
echo "petsurfer-km Done" |& tee -a $LF
exit 0

###############################################

############--------------##################
error_exit:
echo "ERROR:"

exit 1;
###############################################

############--------------##################
parse_args:
set cmdline = ($argv);
while( $#argv != 0 )

  set flag = $argv[1]; shift;
  
  switch($flag)

    case "--sif":
      if($#argv < 1) goto arg1err;
      set sif = $argv[1]; shift;
      setenv PETSURFER_SIF $sif
      breaksw

    case "--apptainer":
      set container = apptainer
      breaksw

    case "--singularity":
      set container = singularity
      breaksw

    case "--docker":
      set container = docker
      breaksw

    case "-fs-license":
    case "--fs-license":
      if($#argv < 1) goto arg1err;
      set fslicense = $argv[1]; shift;
      breaksw
      
    case "--force":
     set ForceUpdate = 1
     breaksw
    case "--no-force":
     set ForceUpdate = 0
     breaksw

    case "--log":
      if($#argv < 1) goto arg1err;
      set LF = $argv[1]; shift;
      breaksw

    case "--nolog":
    case "--no-log":
      set LF = /dev/null
      breaksw

    case "--tmp":
    case "--tmpdir":
      if($#argv < 1) goto arg1err;
      set tmpdir = $argv[1]; shift;
      set cleanup = 0;
      breaksw

    case "--nocleanup":
      set cleanup = 0;
      breaksw

    case "--cleanup":
      set cleanup = 1;
      breaksw

    case "--debug":
      set verbose = 1;
      set echo = 1;
      breaksw

    case "-help":
    case "--help":
      set PrintHelp = 1;
      breaksw

    default:
      if($#bidsdir == 0) then
        set bidsdir = $flag
      else if($#outdir == 0) then
        set outdir = $flag
      else if($#analysislevel == 0) then
        set analysislevel = $flag
      else
       # Build pskm args here 
       set pskmargs = ($pskmargs $flag)
     endif
  endsw

end

goto parse_args_return;
############--------------##################

############--------------##################
check_params:

which $container >& /dev/null
if($status) then
  echo "ERROR: cannot find $container in your path, make sure it is installed on your system"
  foreach c (apptainer singularity docker)
    if($c == $container) continue
    which $c >& /dev/null
    if(! $status) then
      echo "It looks like $c is installed on your system, try running with --$c"
    endif
  end
  exit 1
endif

if($PrintHelp) then
  goto usage_exit;
endif

if($#outdir == 0) then
  echo "ERROR: must spec outdir"
  exit 1;
endif
if($#bidsdir == 0) then
  echo "ERROR: must spec bidsdir"
  exit 1;
endif
if($#analysislevel == 0) then
  echo "ERROR: must analysislevel"
  exit 1;
endif

if($#sif == 0) then
  echo "ERROR: sif not passed or PETSURFER_SIF env var not defined"
  echo "You can get it using one of these methods"
  echo "apptainer pull ~/containers/petsurfer-bids-0.1.3.sif docker://freesurfer/petsurfer-bids:0.1.3"
  echo "docker pull freesurfer/petsurfer-bids:0.2.3"
  echo "singularity pull petsurfer-bids-0.2.1.sif docker://freesurfer/petsurfer-bids:0.2.3"
  exit 1;
endif

if($#fslicense == 0) then
  if($?FREESURFER_HOME == 0) then
    echo "ERROR: no FreeSurfer license passed and FREESURFER_HOME not defined"
    exit 1
  endif
  set fslicense = $FREESURFER_HOME/.license
  if(! -e $fslicense) then
    set fslicense = $FREESURFER_HOME/license
    if(! -e $fslicense) then
      echo "ERROR: no FreeSurfer license passed and cannot find $FREESURFER_HOME/.license or $FREESURFER_HOME/license"
      exit 1
    endif
  endif
endif  

foreach f ($bidsdir $sif $fslicense)
  if(-e $f) continue
  echo "ERROR: cannot find $f"
  exit 1
end

goto check_params_return;
############--------------##################

############--------------##################
arg1err:
  echo "ERROR: flag $flag requires one argument"
  exit 1
############--------------##################
arg2err:
  echo "ERROR: flag $flag requires two arguments"
  exit 1
############--------------##################

############--------------##################
usage_exit:
  echo ""
  echo "petsurfer-km : BIDS app. Wrapper around container to run invividual PETsurfer kinetic modeling"
  echo "  bidsdir outdir analysis_levedl"
  echo "    bidsdir is the path to the BIDS directory with derivatives/{petprep,bloodstream}"
  echo "    outdir is the path to the output, eg, derivativeds/petsurfer"
  echo "    analysis_level is either particpant or group"
  echo " --sif petsurfer.sif : singularity image file (or set PETSURFER_SIF env var)"
  echo " --singularity : use singularity instead of $container"
  echo " --docker : use docker instead of $container"
  echo " --fs-license fs-licensepath : if it can't be found in FREESURFER_HOME"
  echo " --help (needs SIF via PETSURFER_SIF or --sif)"
  echo ""

  if(! $PrintHelp) exit 1;
  echo $VERSION
  cat $0 | awk 'BEGIN{prt=0}{if(prt) print $0; if($1 == "BEGINHELP") prt = 1 }'

  if($#sif == 0 && $?PETSURFER_SIF != 0) then
    set sif = $PETSURFER_SIF
  endif
  if($#sif) then
    set cmd = ($container run --pwd / $sif petsurfer-km --help)
    $cmd
  endif

  exit 1;

#---- Everything below here is printed out as part of help -----#
BEGINHELP
